version: "3.4"

services:
  app:
    image: fuel
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/html/app
    working_dir: /var/www/html/app
  mariadb:
    image: mariadb:11.1.3-jammy
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: test
